
#line 3 "lex.swf5.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE swf5restart(swf5in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int swf5leng;

extern FILE *swf5in, *swf5out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up swf5text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up swf5text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via swf5restart()), so that the user can continue scanning by
	 * just pointing swf5in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when swf5text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int swf5leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow swf5wrap()'s to do buffer switches
 * instead of setting up a fresh swf5in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void swf5restart (FILE *input_file  );
void swf5_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE swf5_create_buffer (FILE *file,int size  );
void swf5_delete_buffer (YY_BUFFER_STATE b  );
void swf5_flush_buffer (YY_BUFFER_STATE b  );
void swf5push_buffer_state (YY_BUFFER_STATE new_buffer  );
void swf5pop_buffer_state (void );

static void swf5ensure_buffer_stack (void );
static void swf5_load_buffer_state (void );
static void swf5_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER swf5_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE swf5_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE swf5_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE swf5_scan_bytes (yyconst char *bytes,int len  );

void *swf5alloc (yy_size_t  );
void *swf5realloc (void *,yy_size_t  );
void swf5free (void *  );

#define yy_new_buffer swf5_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        swf5ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            swf5_create_buffer(swf5in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        swf5ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            swf5_create_buffer(swf5in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *swf5in = (FILE *) 0, *swf5out = (FILE *) 0;

typedef int yy_state_type;

extern int swf5lineno;

int swf5lineno = 1;

extern char *swf5text;
#define yytext_ptr swf5text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up swf5text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	swf5leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 166
#define YY_END_OF_BUFFER 167
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[650] =
    {   0,
        0,    0,    0,    0,  167,  165,  119,  164,  165,  152,
      165,  151,  146,  165,  153,  154,  149,  144,  159,  145,
      160,  150,    3,    3,  162,  142,  140,  143,  141,  161,
      155,  156,  148,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  157,  147,  158,  163,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      164,  125,    0,  115,  113,    0,  126,  132,    0,  116,
      114,    0,  128,  120,  130,  121,  131,  117,  118,  129,
        4,    2,    3,    0,  134,  122,  124,  123,  135,  112,

      112,  112,  112,  112,  112,  112,   19,  112,  112,  112,
      112,  112,  112,  112,  112,   17,   16,  112,  112,  112,
      112,  112,  112,  112,    0,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  133,  127,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,   16,
      112,  112,  112,  112,  112,  112,  112,  112,   63,  112,
      112,  112,  112,  112,  112,  112,  112,  112,    4,    1,
      137,  138,  136,   25,  112,  112,  112,   37,  112,  112,
      112,  112,  112,  112,  112,   15,  112,  112,  112,  112,
       35,  112,  112,   21,  112,  112,   36,  112,  112,  111,

      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,   20,  112,  112,   66,   62,  112,  112,   73,  112,
       55,  110,  112,  112,  109,   72,  112,  112,  112,  112,
      112,  112,  112,  112,  112,   21,   91,  112,   57,  112,
      112,  112,  112,  112,  112,  112,  112,  112,   20,   64,
      139,  112,  112,   13,  112,  112,  112,  112,  112,   11,
       26,  112,  112,  112,  112,  112,  112,  112,  112,  112,
        7,   42,  112,  112,  112,  112,  112,   43,  112,  112,
      112,  112,    5,  112,  112,   24,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,

      112,  112,  112,  112,  112,  112,  112,  112,  108,   58,
      112,  112,  112,  112,  112,  112,   43,  112,  112,  112,
       56,  112,    8,  112,  112,  112,  112,  112,  112,    6,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,   34,  112,
       18,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  104,  112,  103,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,   32,  112,  112,
       22,  112,  112,  112,   38,  112,  112,   31,  112,  112,

      112,  112,   29,  112,   23,  112,  112,   33,   12,  112,
       27,  105,  112,  112,   86,  112,   70,  112,  112,  112,
      112,  112,  112,  112,  112,   65,  112,   67,  112,  112,
       83,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,   33,  112,  112,  112,  112,   14,  112,  112,
      112,   39,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,    9,  112,   10,   30,  112,  112,

      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,   68,  112,  112,
      101,  112,   85,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,   99,   92,  112,  112,   84,  112,
       46,  112,   47,  112,   50,  112,   40,   41,  112,   48,
      112,  112,  112,  112,  112,  112,   74,   77,  112,   76,
      112,  112,   90,  112,   71,  112,   87,  112,   78,  112,
       48,  112,   79,  112,   98,  112,  112,   94,   82,  112,
       28,  112,  112,  112,   45,  112,  112,  112,  112,   61,
      112,   75,   89,  112,  112,  112,  112,  112,  112,   80,

      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
       95,  102,   69,   88,   59,  112,   96,   81,  112,  112,
      112,   52,  112,  112,  112,  106,  107,   60,  112,   93,
      112,  112,   49,  112,   44,   97,  112,  112,  112,  112,
      100,  112,  112,   54,  112,   51,  112,   53,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,    1,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   52,   53,   54,   55,   56,   57,   58,   33,
       29,   30,   31,   32,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,   49,   50,   51,   52,   53,   54,   55,   56,   57,
       58,   33,   59,   60,   61,   62,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[63] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    2,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    2,    2,    2,    2,    2,    2,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    1,    1,
        1,    1
    } ;

static yyconst flex_int16_t yy_base[654] =
    {   0,
        0,    0,   29,    0,  741,  742,  742,  742,  737,  713,
       67,  742,   64,   76,  742,  742,  712,   67,  742,   68,
      742,   70,   82,   89,  742,  742,   63,  711,   65,  742,
      742,  742,  742,    0,  684,  684,   78,   75,   69,   82,
       77,   81,   79,   80,  683,   86,  109,   95,   87,  699,
       80,  742,  114,  742,  742,  105,  681,  112,  116,  116,
      117,  120,  124,  121,  130,   99,  128,  139,  697,  682,
      742,  742,  180,  182,  742,  726,  742,  742,  178,  187,
      742,  725,  742,  742,  742,  742,  742,  742,  742,  742,
      179,  200,  207,    0,  701,  742,  742,  742,  176,    0,

      680,  687,  159,  673,  676,  168,    0,  673,  669,  686,
      674,  667,  670,  663,  662,    0,  153,  667,  679,  158,
      667,  674,  676,  671,  212,  661,  189,  654,  658,  670,
      662,  663,  155,  653,  650,  658,  646,  742,  742,  661,
      660,   61,  191,  201,  641,  646,  187,  640,  640,  202,
      198,  213,  212,  655,  646,  195,  637,  652,  651,  142,
      635,  633,  643,  215,  649,  225,  632,  631,  250,    0,
      742,  742,  655,    0,  646,  634,  640,    0,  203,  643,
      638,  630,  636,  628,  620,    0,  635,  208,  622,  616,
        0,  628,  630,    0,  613,  620,    0,  606,  608,  255,

      625,  613,  606,  606,  609,  605,  603,  615,  618,  615,
      614,    0,  606,  609,    0,    0,  602,  603,    0,  605,
      601,    0,  599,  610,  232,    0,  590,  590,  599,  599,
      601,  587,  583,  582,  582,  245,    0,  246,    0,  581,
      592,  242,  593,  580,  581,  587,  229,  579,  589,    0,
      742,  582,  586,    0,  590,  581,  568,  568,  578,    0,
        0,  581,  565,  575,  565,  576,  580,  560,  243,  573,
        0,    0,  572,  562,  554,  557,  573,  554,  552,  568,
      558,  564,    0,  553,  562,    0,  563,  219,  561,  559,
      551,  557,  560,  258,  540,  556,  540,  543,  552,  553,

      542,  544,  548,  534,  545,  545,  531,  542,    0,    0,
      541,  540,  543,  542,  522,  521,  257,  526,  519,  520,
        0,  520,    0,  518,  515,  520,  521,  527,  528,    0,
      521,  516,  516,  509,  512,  517,  509,  522,  504,  503,
      507,  514,  504,  499,  501,  497,  506,  508,    0,  506,
        0,  503,  245,  505,  504,  490,  488,  493,  487,  486,
      501,  494,  500,    0,  493,    0,  480,  483,  481,  492,
      474,  475,  489,  471,  472,  477,  482,  470,  469,  256,
      482,  467,  477,  465,  481,  460,  479,    0,  458,  458,
        0,  476,  461,  470,  488,  472,  469,    0,  449,  452,

      468,  467,    0,  454,    0,  459,  444,    0,    0,  447,
        0,  266,  449,  442,    0,  460,    0,  458,  450,  440,
      447,  455,  443,  434,  433,    0,  440,    0,  450,  431,
        0,  448,  429,  445,  437,  438,  435,  438,  433,  423,
      439,  265,  430,  435,  436,  423,  430,    0,  414,  419,
      414,    0,  418,  425,  420,  419,  414,  413,  410,  419,
      409,  401,  409,  414,  416,  410,  397,  411,  414,  413,
      408,  398,  268,  403,  392,  384,  396,  387,  394,  385,
      399,  384,  397,  400,  394,  392,  397,  390,  379,  390,
      380,  373,  380,  386,    0,  385,    0,    0,  384,  373,

      382,  385,  380,  379,  361,  362,  377,  379,  356,  358,
      357,  361,  370,  356,  371,  347,  368,    0,  356,  351,
        0,  359,    0,  348,  358,  346,  356,  345,  342,  341,
      358,  339,  350,  350,    0,    0,  265,  349,    0,  336,
        0,  341,    0,  347,  338,  349,    0,    0,  341,    0,
      330,  336,  346,  328,  336,  340,    0,    0,  331,    0,
      322,  337,    0,  326,    0,  338,    0,  337,    0,  332,
      331,  323,    0,  314,    0,  326,  313,    0,    0,  316,
        0,  309,  317,  323,    0,  318,  301,  304,  309,    0,
      318,    0,    0,  315,  307,  306,  301,  294,  312,  329,

      295,  294,  291,  299,  306,  307,  289,  289,  302,  292,
        0,    0,    0,    0,    0,  289,    0,    0,  296,  295,
      293,    0,  282,  288,  274,    0,    0,    0,  280,    0,
      296,  291,  281,  285,    0,    0,  279,  279,  260,  264,
        0,  266,  259,    0,  262,    0,   92,    0,  742,  317,
      320,  322,   66
    } ;

static yyconst flex_int16_t yy_def[654] =
    {   0,
      649,    1,    1,    3,  649,  649,  649,  649,  649,  649,
      650,  649,  649,  651,  649,  649,  649,  649,  649,  649,
      649,  649,  649,  649,  649,  649,  649,  649,  649,  649,
      649,  649,  649,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  649,  649,  649,  649,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      649,  649,  650,  650,  649,  650,  649,  649,  651,  651,
      649,  651,  649,  649,  649,  649,  649,  649,  649,  649,
      649,  649,  649,  653,  649,  649,  649,  649,  649,  652,

      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  649,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  649,  649,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  649,  653,
      649,  649,  649,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  649,

      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      649,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,

      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,

      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,

      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,

      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,    0,  649,
      649,  649,  649
    } ;

static yyconst flex_int16_t yy_nxt[805] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   24,
       24,   24,   25,   26,   27,   28,   29,   30,   31,    6,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       34,   42,   34,   34,   43,   34,   44,   45,   46,   34,
       47,   48,   49,   34,   50,   51,   34,   34,   52,   53,
       54,   55,   56,   57,   58,   59,   60,  170,   61,   74,
       62,   77,   75,   63,   64,   65,   66,   67,   80,   84,
       68,   88,   86,   69,   81,   70,   89,   95,   96,   78,
       98,   99,   85,   87,  217,   90,   76,   91,  175,   92,

       92,   92,   92,   93,   91,   82,   93,   93,   93,   93,
       93,  103,  106,  109,  114,  111,  118,  120,  104,  116,
      136,  137,  107,  110,  115,  105,  119,  117,  108,  112,
      123,  125,  128,  121,  132,  113,  124,  133,   94,  138,
      648,  140,  126,  158,  134,  143,  127,  129,  130,  159,
      131,  141,  104,  144,  149,  153,  101,  145,  116,  105,
      109,  151,  147,  107,  115,  148,  150,  156,  154,  146,
      110,  152,  123,  139,  155,  160,  162,  157,  124,  163,
       80,  161,   74,  121,   74,   75,   81,   75,  209,   80,
      239,  164,  165,  240,  166,   81,  169,  169,  169,  169,

      169,  172,  173,  176,  190,  191,  180,   82,  210,   76,
      177,   76,  181,  194,  195,   91,   82,   92,   92,   92,
       92,   93,   91,  222,   93,   93,   93,   93,   93,  200,
      200,  200,  200,  200,  202,  218,  219,  226,  255,  180,
      223,  203,  177,  227,  192,  181,  193,  230,  244,  228,
      236,  195,  229,  190,  191,  256,  231,  353,  248,  232,
      264,  265,  245,  233,  354,  246,  207,  169,  169,  169,
      169,  169,  200,  200,  200,  200,  200,  292,  303,  306,
      319,  320,  304,  307,  264,  265,  293,  311,  337,  305,
      308,  360,  312,  382,  313,  387,  314,  338,  413,  463,

      438,  519,  489,  647,  646,  361,  439,  464,  345,  490,
      645,  576,  644,  643,  642,  520,  577,   73,   73,   73,
       79,   79,   79,  100,  100,  641,  640,  639,  638,  637,
      636,  635,  634,  633,  632,  631,  630,  629,  628,  627,
      626,  625,  624,  623,  622,  621,  620,  619,  618,  617,
      616,  615,  614,  613,  612,  611,  610,  609,  608,  607,
      606,  605,  604,  603,  602,  601,  600,  599,  598,  597,
      596,  595,  594,  593,  592,  591,  590,  589,  588,  587,
      586,  585,  584,  583,  582,  581,  580,  579,  578,  575,
      574,  573,  572,  571,  570,  569,  568,  567,  566,  565,

      564,  563,  562,  561,  560,  559,  558,  557,  556,  555,
      554,  553,  552,  551,  550,  549,  548,  547,  546,  545,
      544,  543,  542,  541,  540,  539,  538,  537,  536,  535,
      534,  533,  532,  531,  530,  529,  528,  527,  526,  525,
      524,  523,  522,  521,  518,  517,  516,  515,  514,  513,
      512,  511,  510,  509,  508,  507,  506,  505,  504,  503,
      502,  501,  500,  499,  498,  497,  496,  495,  494,  493,
      492,  491,  488,  487,  486,  485,  484,  483,  482,  481,
      480,  479,  478,  477,  476,  475,  474,  473,  472,  471,
      470,  469,  468,  467,  466,  465,  462,  461,  460,  459,

      458,  457,  456,  455,  454,  453,  452,  451,  450,  449,
      448,  447,  446,  445,  444,  443,  442,  441,  440,  437,
      436,  435,  434,  433,  432,  431,  430,  429,  428,  427,
      426,  425,  424,  423,  422,  421,  420,  419,  418,  417,
      416,  415,  414,  412,  411,  410,  409,  408,  407,  406,
      405,  404,  403,  402,  401,  400,  399,  398,  397,  396,
      395,  394,  393,  392,  391,  390,  389,  388,  387,  386,
      385,  384,  383,  381,  380,  379,  378,  377,  376,  375,
      374,  373,  372,  371,  370,  369,  368,  367,  366,  365,
      364,  363,  362,  359,  358,  357,  356,  355,  352,  351,

      350,  349,  348,  347,  346,  345,  344,  343,  342,  341,
      340,  339,  336,  335,  334,  333,  332,  331,  330,  329,
      328,  327,  326,  325,  324,  323,  322,  321,  318,  317,
      316,  315,  310,  309,  302,  301,  300,  299,  298,  297,
      296,  295,  294,  291,  290,  259,  289,  288,  287,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  274,  273,  272,  271,  270,  269,  268,  267,  266,
      263,  262,  261,  260,  259,  258,  257,  254,  253,  252,
      251,  250,  249,  247,  243,  242,  241,  197,  238,  237,
      235,  234,  225,  224,  221,  220,  216,  215,  214,  213,

      212,  211,  208,  207,  206,  205,  204,  201,  199,  198,
      197,  196,  193,  192,  189,  188,  187,  186,  185,  184,
      183,  182,  179,  178,  175,  174,  171,  649,  649,  168,
      167,  142,  135,  122,  102,  101,   97,   83,   72,   71,
      649,    5,  649,  649,  649,  649,  649,  649,  649,  649,
      649,  649,  649,  649,  649,  649,  649,  649,  649,  649,
      649,  649,  649,  649,  649,  649,  649,  649,  649,  649,
      649,  649,  649,  649,  649,  649,  649,  649,  649,  649,
      649,  649,  649,  649,  649,  649,  649,  649,  649,  649,
      649,  649,  649,  649,  649,  649,  649,  649,  649,  649,

      649,  649,  649,  649
    } ;

static yyconst flex_int16_t yy_chk[805] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    3,    3,    3,  653,    3,   11,
        3,   13,   11,    3,    3,    3,    3,    3,   14,   18,
        3,   22,   20,    3,   14,    3,   22,   27,   27,   13,
       29,   29,   18,   20,  142,   22,   11,   23,  142,   23,

       23,   23,   23,   23,   24,   14,   24,   24,   24,   24,
       24,   37,   38,   39,   41,   40,   43,   44,   37,   42,
       51,   51,   38,   39,   41,   37,   43,   42,   38,   40,
       46,   47,   48,   44,   49,   40,   46,   49,   23,   53,
      647,   56,   47,   66,   49,   58,   47,   48,   48,   66,
       48,   56,   58,   59,   61,   64,   56,   59,   62,   58,
       60,   63,   60,   59,   61,   60,   62,   65,   64,   59,
       60,   63,   67,   53,   64,   67,   68,   65,   67,   68,
       79,   67,   73,   65,   74,   73,   79,   74,  133,   80,
      160,   68,   68,  160,   68,   80,   91,   91,   91,   91,

       91,   99,   99,  103,  117,  117,  106,   79,  133,   73,
      103,   74,  106,  120,  120,   92,   80,   92,   92,   92,
       92,   92,   93,  147,   93,   93,   93,   93,   93,  125,
      125,  125,  125,  125,  127,  143,  144,  150,  179,  144,
      147,  127,  143,  150,  151,  144,  152,  153,  164,  151,
      156,  156,  152,  150,  150,  179,  153,  288,  166,  153,
      188,  188,  164,  153,  288,  164,  166,  169,  169,  169,
      169,  169,  200,  200,  200,  200,  200,  225,  236,  238,
      247,  247,  236,  238,  225,  225,  225,  242,  269,  236,
      238,  294,  242,  317,  242,  353,  242,  269,  353,  412,

      380,  473,  442,  645,  643,  294,  380,  412,  317,  442,
      642,  537,  640,  639,  638,  473,  537,  650,  650,  650,
      651,  651,  651,  652,  652,  637,  634,  633,  632,  631,
      629,  625,  624,  623,  621,  620,  619,  616,  610,  609,
      608,  607,  606,  605,  604,  603,  602,  601,  600,  599,
      598,  597,  596,  595,  594,  591,  589,  588,  587,  586,
      584,  583,  582,  580,  577,  576,  574,  572,  571,  570,
      568,  566,  564,  562,  561,  559,  556,  555,  554,  553,
      552,  551,  549,  546,  545,  544,  542,  540,  538,  534,
      533,  532,  531,  530,  529,  528,  527,  526,  525,  524,

      522,  520,  519,  517,  516,  515,  514,  513,  512,  511,
      510,  509,  508,  507,  506,  505,  504,  503,  502,  501,
      500,  499,  496,  494,  493,  492,  491,  490,  489,  488,
      487,  486,  485,  484,  483,  482,  481,  480,  479,  478,
      477,  476,  475,  474,  472,  471,  470,  469,  468,  467,
      466,  465,  464,  463,  462,  461,  460,  459,  458,  457,
      456,  455,  454,  453,  451,  450,  449,  447,  446,  445,
      444,  443,  441,  440,  439,  438,  437,  436,  435,  434,
      433,  432,  430,  429,  427,  425,  424,  423,  422,  421,
      420,  419,  418,  416,  414,  413,  410,  407,  406,  404,

      402,  401,  400,  399,  397,  396,  395,  394,  393,  392,
      390,  389,  387,  386,  385,  384,  383,  382,  381,  379,
      378,  377,  376,  375,  374,  373,  372,  371,  370,  369,
      368,  367,  365,  363,  362,  361,  360,  359,  358,  357,
      356,  355,  354,  352,  350,  348,  347,  346,  345,  344,
      343,  342,  341,  340,  339,  338,  337,  336,  335,  334,
      333,  332,  331,  329,  328,  327,  326,  325,  324,  322,
      320,  319,  318,  316,  315,  314,  313,  312,  311,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  293,  292,  291,  290,  289,  287,  285,

      284,  282,  281,  280,  279,  278,  277,  276,  275,  274,
      273,  270,  268,  267,  266,  265,  264,  263,  262,  259,
      258,  257,  256,  255,  253,  252,  249,  248,  246,  245,
      244,  243,  241,  240,  235,  234,  233,  232,  231,  230,
      229,  228,  227,  224,  223,  221,  220,  218,  217,  214,
      213,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  201,  199,  198,  196,  195,  193,  192,  190,  189,
      187,  185,  184,  183,  182,  181,  180,  177,  176,  175,
      173,  168,  167,  165,  163,  162,  161,  159,  158,  157,
      155,  154,  149,  148,  146,  145,  141,  140,  137,  136,

      135,  134,  132,  131,  130,  129,  128,  126,  124,  123,
      122,  121,  119,  118,  115,  114,  113,  112,  111,  110,
      109,  108,  105,  104,  102,  101,   95,   82,   76,   70,
       69,   57,   50,   45,   36,   35,   28,   17,   10,    9,
        5,  649,  649,  649,  649,  649,  649,  649,  649,  649,
      649,  649,  649,  649,  649,  649,  649,  649,  649,  649,
      649,  649,  649,  649,  649,  649,  649,  649,  649,  649,
      649,  649,  649,  649,  649,  649,  649,  649,  649,  649,
      649,  649,  649,  649,  649,  649,  649,  649,  649,  649,
      649,  649,  649,  649,  649,  649,  649,  649,  649,  649,

      649,  649,  649,  649
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int swf5_flex_debug;
int swf5_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *swf5text;
#line 1 "swf5compiler.flex"
#line 2 "swf5compiler.flex"

#include <math.h>
#include <string.h>

#include "compile.h"
#include "action.h"
#include "blocks/error.h"
#include "swf5compiler.tab.h" /* defines token types */

static int swf5debug;

static const char *lexBuffer = NULL;
static int lexBufferLen = 0;

static int  sLineNumber = 0;
static char szLine[1024];
static char msgbufs[2][1024] = { {0}, {0} }, *msgline = {0};
static int  column = 0;

static void comment();
static void comment1();
static void count();
static void countline();
static void warning(char *msg);

#define YY_INPUT(buf,result,max_size) result=lexBufferInput(buf, max_size)

/* thanks to the prolific and brilliant Raff: */
static int lexBufferInput(char *buf, int max_size)
{
  int l = lexBufferLen > max_size ? max_size : lexBufferLen;

  if (lexBufferLen <= 0)
    return YY_NULL;

  memcpy(buf, lexBuffer, l);
  lexBuffer += l;
  lexBufferLen -= l;
  return l;
}

        /* very inefficient method of unescaping strings */
static void unescape(char *buf)
{
  char *p, *p1;

  for (p1=buf; (p=strchr(p1, '\\')) != 0; p1 = p+1) {
    switch(p[1])
    {
    case 'b' : p[1] = '\b'; break;
    case 'f' : p[1] = '\f'; break;
    case 'n' : p[1] = '\n'; break;
    case 'r' : p[1] = '\r'; break;
    case 't' : p[1] = '\t'; break;
    case 'x' :
    case 'u' : warning("unsupported escape sequence");
    }
    strcpy(p, p+1);
  }
}

void swf5ParseInit(const char *script, int debug)
{
  checkByteOrder();
  swf5restart(NULL);

  swf5debug = debug;

  lexBuffer = script;
  lexBufferLen = strlen(script);
  sLineNumber = 0;
  column = 0;
  msgline = msgbufs[0];
}


#line 82 "swf5compiler.flex"
 // forward declaration needed by the following function
#ifndef YY_PROTO
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
#endif
 static void yyunput YY_PROTO(( int c, char *buf_ptr ));

 void do_unput5(const char c) { unput(c); }
#line 936 "lex.swf5.c"

#define INITIAL 0
#define asm 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int swf5wrap (void );
#else
extern int swf5wrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( swf5text, swf5leng, 1, swf5out )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( swf5in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( swf5in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, swf5in))==0 && ferror(swf5in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(swf5in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int swf5lex (void);

#define YY_DECL int swf5lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after swf5text and swf5leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 98 "swf5compiler.flex"


#line 1093 "lex.swf5.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! swf5in )
			swf5in = stdin;

		if ( ! swf5out )
			swf5out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			swf5ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				swf5_create_buffer(swf5in,YY_BUF_SIZE );
		}

		swf5_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of swf5text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 650 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 742 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 100 "swf5compiler.flex"
{ count();	swf5lval.intVal = strtoul(swf5text, NULL, 0);
					return INTEGER;		}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 102 "swf5compiler.flex"
{ count();	swf5lval.intVal = strtoul(swf5text, NULL, 0);
					return INTEGER;		}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 104 "swf5compiler.flex"
{ count();	swf5lval.intVal = atoi(swf5text);
					return INTEGER;		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 106 "swf5compiler.flex"
{ count();	swf5lval.doubleVal = atof(swf5text);
					return DOUBLE; 		}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 108 "swf5compiler.flex"
{ count();	swf5lval.intVal = 1;
					return BOOLEAN;		}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 110 "swf5compiler.flex"
{ count();	swf5lval.intVal = 0;
					return BOOLEAN;		}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 112 "swf5compiler.flex"
{ count();	return NULLVAL;		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 113 "swf5compiler.flex"
{ count();	return BREAK;		}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 114 "swf5compiler.flex"
{ count();	return CONTINUE;	}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 115 "swf5compiler.flex"
{ count();	return FUNCTION;	}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 116 "swf5compiler.flex"
{ count();	return ELSE;		}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 117 "swf5compiler.flex"
{ count();	return SWITCH;		}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 118 "swf5compiler.flex"
{ count();	return CASE;		}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 119 "swf5compiler.flex"
{ count();	return DEFAULT;		}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 120 "swf5compiler.flex"
{ count();	return FOR;		}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 121 "swf5compiler.flex"
{ count();	return IN;		}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 122 "swf5compiler.flex"
{ count();	return IF;		}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 123 "swf5compiler.flex"
{ count();	return WHILE;		}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 124 "swf5compiler.flex"
{ count();	return DO;		}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 125 "swf5compiler.flex"
{ count();	return VAR;		}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 126 "swf5compiler.flex"
{ count();	return NEW;		}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 127 "swf5compiler.flex"
{ count();	return DELETE;		}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 128 "swf5compiler.flex"
{ count();	return RETURN;		}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 129 "swf5compiler.flex"
{ count();	return WITH;		}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 130 "swf5compiler.flex"
{ count();	BEGIN(asm); return ASM;		}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 131 "swf5compiler.flex"
{ count();	return EVAL;		}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 132 "swf5compiler.flex"
{ count();	return TYPEOF; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 133 "swf5compiler.flex"
{ count();	return INSTANCEOF; }
	YY_BREAK
/* legacy functions */
case 29:
YY_RULE_SETUP
#line 136 "swf5compiler.flex"
{ count();	return RANDOM;	}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 137 "swf5compiler.flex"
{ count();	return GETTIMER;	}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 138 "swf5compiler.flex"
{ count();	return LENGTH;	}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 139 "swf5compiler.flex"
{ count();	return CONCAT;	}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 140 "swf5compiler.flex"
{ count();	return SUBSTR;	}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 141 "swf5compiler.flex"
{ count();	return TRACE;	}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 142 "swf5compiler.flex"
{ count();	return INT;	}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 143 "swf5compiler.flex"
{ count();	return ORD;	}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 144 "swf5compiler.flex"
{ count();	return CHR;	}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 145 "swf5compiler.flex"
{ count();	return GETURL;	}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 146 "swf5compiler.flex"
{ count();	return GETURL1;	}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 147 "swf5compiler.flex"
{ count();	return NEXTFRAME;	}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 148 "swf5compiler.flex"
{ count();	return PREVFRAME;	}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 149 "swf5compiler.flex"
{ count();	return PLAY;		}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 150 "swf5compiler.flex"
{ count();	return STOP;		}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 151 "swf5compiler.flex"
{ count();	return TOGGLEQUALITY;	}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 152 "swf5compiler.flex"
{ count();	return STOPSOUNDS;	}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 153 "swf5compiler.flex"
{ count();	return CALLFRAME;	}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 154 "swf5compiler.flex"
{ count();	return GOTOFRAME;	}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 155 "swf5compiler.flex"
{ count();	return SETTARGET;	}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 156 "swf5compiler.flex"
{ count();	return LOADVARIABLES;	}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 157 "swf5compiler.flex"
{ count();	return LOADMOVIE;	}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 158 "swf5compiler.flex"
{ count();	return LOADVARIABLESNUM;	}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 159 "swf5compiler.flex"
{ count();	return LOADMOVIENUM;	}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 160 "swf5compiler.flex"
{ count();	return DUPLICATEMOVIECLIP; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 161 "swf5compiler.flex"
{ count();	return REMOVEMOVIECLIP; }
	YY_BREAK
/* assembler ops */

case 55:
YY_RULE_SETUP
#line 165 "swf5compiler.flex"
{ count();	return DUP; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 166 "swf5compiler.flex"
{ count();	return SWAP; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 167 "swf5compiler.flex"
{ count();	return POP; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 168 "swf5compiler.flex"
{ count();	return PUSH; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 169 "swf5compiler.flex"
{ count();	return SETREGISTER; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 170 "swf5compiler.flex"
{ count();	return CALLFUNCTION; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 171 "swf5compiler.flex"
{ count();	return CALLMETHOD; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 172 "swf5compiler.flex"
{ count();	return AND; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 173 "swf5compiler.flex"
{ count();	return OR; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 174 "swf5compiler.flex"
{ count();	return XOR; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 175 "swf5compiler.flex"
{ count();	return MODULO; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 176 "swf5compiler.flex"
{ count();	return ADD; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 177 "swf5compiler.flex"
{ count();	return ADD; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 178 "swf5compiler.flex"
{ count();	return LESSTHAN; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 179 "swf5compiler.flex"
{ count();	return LESSTHAN; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 180 "swf5compiler.flex"
{ count();	return EQUALS; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 181 "swf5compiler.flex"
{ count();	return EQUALS; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 182 "swf5compiler.flex"
{ count();	return INC; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 183 "swf5compiler.flex"
{ count();	return DEC; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 184 "swf5compiler.flex"
{ count();	return ENUMERATE; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 185 "swf5compiler.flex"
{ count();	return INITOBJECT; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 186 "swf5compiler.flex"
{ count();	return INITARRAY; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 187 "swf5compiler.flex"
{ count();	return GETMEMBER; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 188 "swf5compiler.flex"
{ count();	return SETMEMBER; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 189 "swf5compiler.flex"
{ count();	return SHIFTLEFT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 190 "swf5compiler.flex"
{ count();	return SHIFTRIGHT; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 191 "swf5compiler.flex"
{ count();	return SHIFTRIGHT2; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 192 "swf5compiler.flex"
{ count();	return VAREQUALS; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 193 "swf5compiler.flex"
{ count();	return OLDADD; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 194 "swf5compiler.flex"
{ count();	return SUBTRACT; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 195 "swf5compiler.flex"
{ count();	return MULTIPLY; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 196 "swf5compiler.flex"
{ count();	return DIVIDE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 197 "swf5compiler.flex"
{ count();	return OLDEQUALS; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 198 "swf5compiler.flex"
{ count();	return OLDLESSTHAN; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 199 "swf5compiler.flex"
{ count();	return LOGICALAND; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 200 "swf5compiler.flex"
{ count();	return LOGICALOR; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 201 "swf5compiler.flex"
{ count();	return NOT; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 202 "swf5compiler.flex"
{ count();	return STRINGEQ; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 203 "swf5compiler.flex"
{ count();	return STRINGLENGTH; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 204 "swf5compiler.flex"
{ count();	return SUBSTRING; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 205 "swf5compiler.flex"
{ count();	return GETVARIABLE; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 206 "swf5compiler.flex"
{ count();	return SETVARIABLE; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 207 "swf5compiler.flex"
{ count();	return SETTARGETEXPRESSION; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 208 "swf5compiler.flex"
{ count();	return STARTDRAG; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 209 "swf5compiler.flex"
{ count();	return STOPDRAG; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 210 "swf5compiler.flex"
{ count();	return STRINGLESSTHAN; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 211 "swf5compiler.flex"
{ count();	return MBLENGTH; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 212 "swf5compiler.flex"
{ count();	return MBSUBSTRING; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 213 "swf5compiler.flex"
{ count();	return MBORD; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 214 "swf5compiler.flex"
{ count();	return MBCHR; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 215 "swf5compiler.flex"
{ count();	return BRANCHALWAYS; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 216 "swf5compiler.flex"
{ count();	return BRANCHALWAYS; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 217 "swf5compiler.flex"
{ count();	return BRANCHIFTRUE; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 218 "swf5compiler.flex"
{ count();	return POST; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 219 "swf5compiler.flex"
{ count();	return GET; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 220 "swf5compiler.flex"
{ count();	return END;		}
	YY_BREAK

case 111:
YY_RULE_SETUP
#line 223 "swf5compiler.flex"
{ count();	swf5lval.str = strdup(swf5text+2);
					return REGISTER;	}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 227 "swf5compiler.flex"
{ count();	swf5lval.str = strdup(swf5text);
					return IDENTIFIER;	}
	YY_BREAK
case 113:
/* rule 113 can match eol */
YY_RULE_SETUP
#line 230 "swf5compiler.flex"
{ count();	swf5lval.str = strdup(swf5text+1);
					swf5lval.str[strlen(swf5lval.str)-1]=0;
                                        unescape(swf5lval.str);
					return STRING;		}
	YY_BREAK
case 114:
/* rule 114 can match eol */
YY_RULE_SETUP
#line 235 "swf5compiler.flex"
{ count();	swf5lval.str = strdup(swf5text+1);
					swf5lval.str[strlen(swf5lval.str)-1]=0;
                                        unescape(swf5lval.str);
					return STRING; 		}
	YY_BREAK
case 115:
/* rule 115 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up swf5text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up swf5text again */
YY_RULE_SETUP
#line 240 "swf5compiler.flex"
{ count();	swf5lval.str = strdup("");
					warning("Unterminated string!");
					return STRING;		}
	YY_BREAK
case 116:
/* rule 116 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up swf5text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up swf5text again */
YY_RULE_SETUP
#line 244 "swf5compiler.flex"
{ count();	swf5lval.str = strdup("");
					warning("Unterminated string!");
					return STRING;		}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 248 "swf5compiler.flex"
{ count();	comment();		}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 249 "swf5compiler.flex"
{ count();	comment1();		}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 250 "swf5compiler.flex"
{ count(); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 252 "swf5compiler.flex"
{ count();	return INCR; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 253 "swf5compiler.flex"
{ count();	return DECR; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 254 "swf5compiler.flex"
{ count();	return LE; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 255 "swf5compiler.flex"
{ count();	return GE; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 256 "swf5compiler.flex"
{ count();	return EQ; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 257 "swf5compiler.flex"
{ count();	return NE; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 258 "swf5compiler.flex"
{ count();	return LAN; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 259 "swf5compiler.flex"
{ count();	return LOR; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 260 "swf5compiler.flex"
{ count();	return MEQ; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 261 "swf5compiler.flex"
{ count();	return DEQ; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 262 "swf5compiler.flex"
{ count();	return IEQ; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 263 "swf5compiler.flex"
{ count();	return SEQ; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 264 "swf5compiler.flex"
{ count();	return AEQ; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 265 "swf5compiler.flex"
{ count();	return OEQ; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 266 "swf5compiler.flex"
{ count();	return SHL; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 267 "swf5compiler.flex"
{ count();	return SHR; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 268 "swf5compiler.flex"
{ count();	return SHR2; }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 269 "swf5compiler.flex"
{ count();	return SHLEQ; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 270 "swf5compiler.flex"
{ count();	return SHREQ; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 271 "swf5compiler.flex"
{ count();	return SHR2EQ; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 273 "swf5compiler.flex"
{ count();	return '<'; }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 274 "swf5compiler.flex"
{ count();	return '>'; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 275 "swf5compiler.flex"
{ count();	return ';'; }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 276 "swf5compiler.flex"
{ count();	return '='; }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 277 "swf5compiler.flex"
{ count();	return '+'; }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 278 "swf5compiler.flex"
{ count();	return '-'; }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 279 "swf5compiler.flex"
{ count();	return '&'; }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 280 "swf5compiler.flex"
{ count();	return '|'; }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 281 "swf5compiler.flex"
{ count();	return '^'; }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 282 "swf5compiler.flex"
{ count();	return '*'; }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 283 "swf5compiler.flex"
{ count();	return '/'; }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 284 "swf5compiler.flex"
{ count();	return '%'; }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 285 "swf5compiler.flex"
{ count();	return '!'; }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 286 "swf5compiler.flex"
{ count();	return '('; }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 287 "swf5compiler.flex"
{ count();	return ')'; }
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 288 "swf5compiler.flex"
{ count();	return '['; }
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 289 "swf5compiler.flex"
{ count();	return ']'; }
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 290 "swf5compiler.flex"
{ count();	return '{'; }
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 291 "swf5compiler.flex"
{ count();	BEGIN(0); return '}'; }
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 292 "swf5compiler.flex"
{ count();	return ','; }
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 293 "swf5compiler.flex"
{ count();	return '.'; }
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 294 "swf5compiler.flex"
{ count();	return '?'; }
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 295 "swf5compiler.flex"
{ count();	return ':'; }
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 296 "swf5compiler.flex"
{ count();	return '~'; }
	YY_BREAK
case 164:
/* rule 164 can match eol */
YY_RULE_SETUP
#line 298 "swf5compiler.flex"
{ count();	strcpy(szLine, swf5text + 1);
					countline();	yyless(1);	}
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 301 "swf5compiler.flex"
SWF_error("Unrecognized character: %s\n", swf5text);
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 303 "swf5compiler.flex"
ECHO;
	YY_BREAK
#line 2040 "lex.swf5.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(asm):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed swf5in at a new source and called
			 * swf5lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = swf5in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( swf5wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * swf5text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of swf5lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					swf5realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			swf5restart(swf5in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 650 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 650 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 649);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up swf5text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					swf5restart(swf5in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( swf5wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve swf5text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void swf5restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        swf5ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            swf5_create_buffer(swf5in,YY_BUF_SIZE );
	}

	swf5_init_buffer(YY_CURRENT_BUFFER,input_file );
	swf5_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void swf5_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		swf5pop_buffer_state();
	 *		swf5push_buffer_state(new_buffer);
     */
	swf5ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	swf5_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (swf5wrap()) processing, but the only time this flag
	 * is looked at is after swf5wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void swf5_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	swf5in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE swf5_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) swf5alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in swf5_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) swf5alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in swf5_create_buffer()" );

	b->yy_is_our_buffer = 1;

	swf5_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with swf5_create_buffer()
 * 
 */
    void swf5_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		swf5free((void *) b->yy_ch_buf  );

	swf5free((void *) b  );
}

#ifndef _UNISTD_H /* assume unistd.h has isatty() for us */
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __THROW /* this is a gnuism */
extern int isatty (int ) __THROW;
#else
extern int isatty (int );
#endif
#ifdef __cplusplus
}
#endif
#endif
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a swf5restart() or at EOF.
 */
    static void swf5_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	swf5_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then swf5_init_buffer was _probably_
     * called from swf5restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void swf5_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		swf5_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void swf5push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	swf5ensure_buffer_stack();

	/* This block is copied from swf5_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from swf5_switch_to_buffer. */
	swf5_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void swf5pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	swf5_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		swf5_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void swf5ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)swf5alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)swf5realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE swf5_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) swf5alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in swf5_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	swf5_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to swf5lex() will
 * scan from a @e copy of @a str.
 * @param str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       swf5_scan_bytes() instead.
 */
YY_BUFFER_STATE swf5_scan_string (yyconst char * yystr )
{
    
	return swf5_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to swf5lex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE swf5_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) swf5alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in swf5_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = swf5_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in swf5_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up swf5text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		swf5text[swf5leng] = (yy_hold_char); \
		(yy_c_buf_p) = swf5text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		swf5leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int swf5get_lineno  (void)
{
        
    return swf5lineno;
}

/** Get the input stream.
 * 
 */
FILE *swf5get_in  (void)
{
        return swf5in;
}

/** Get the output stream.
 * 
 */
FILE *swf5get_out  (void)
{
        return swf5out;
}

/** Get the length of the current token.
 * 
 */
int swf5get_leng  (void)
{
        return swf5leng;
}

/** Get the current token.
 * 
 */

char *swf5get_text  (void)
{
        return swf5text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void swf5set_lineno (int  line_number )
{
    
    swf5lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see swf5_switch_to_buffer
 */
void swf5set_in (FILE *  in_str )
{
        swf5in = in_str ;
}

void swf5set_out (FILE *  out_str )
{
        swf5out = out_str ;
}

int swf5get_debug  (void)
{
        return swf5_flex_debug;
}

void swf5set_debug (int  bdebug )
{
        swf5_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from swf5lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    swf5in = stdin;
    swf5out = stdout;
#else
    swf5in = (FILE *) 0;
    swf5out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * swf5lex_init()
     */
    return 0;
}

/* swf5lex_destroy is for both reentrant and non-reentrant scanners. */
int swf5lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		swf5_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		swf5pop_buffer_state();
	}

	/* Destroy the stack itself. */
	swf5free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * swf5lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *swf5alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *swf5realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void swf5free (void * ptr )
{
	free( (char *) ptr );	/* see swf5realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 303 "swf5compiler.flex"


static int getinput() {
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
}

int swf5wrap()
{
  return 1;
}

static void countline()
{
  if(sLineNumber != 0)
    msgline[column] = 0;

  ++sLineNumber;
  column = 0;
  msgline = msgbufs[sLineNumber & 1];
}

static int LineNumber(void)
{
   return (sLineNumber + 1);
}

static int ColumnNumber(void)
{
   return column;
}

static char *LineText(void)
{
  msgline[column] = 0;
  return msgline;
}

static void comment()
{
   // Handle block comments

   int c, c1;

loop:
   // We have the start of a comment so look skip everything up to the
   // end of the comment character
   while ((c = getinput()) != '*' && c != EOF)
   {
      if(column < 1023)
         msgline[column] = c;

      ++column;

      // keep the line number in synch
      if (c == '\n')
      {
         // start the output (matches the algorithim in the lexx above)
	 countline();
      }

      if (swf5debug) putchar(c);
   }

   // is this the end of comment character
   if ((c1 = getinput()) != '/' && c != EOF)
   {
      // false start as this was no end of comment
      do_unput5(c1);
      goto loop;
   }

   // write out the start of the end of comment
   if (c != EOF)
      if (swf5debug) putchar(c);

   // write out the end of the end of comment
   if (c1 != EOF) 
      if (swf5debug) putchar(c1);
}

static void comment1()
{
   // Handle comment of type 1 (ie '//')

   int c;

   // this is a line comment
   while ((c = getinput()) != '\n' && c != EOF)
   {
      if (swf5debug) putchar(c);

      if(column < 1023)
         msgline[column] = c;

      ++column;
   };

   // keep the line number in synch
   if (c == '\n')
   {
      if (swf5debug) putchar(c);

      countline();
   }
}

static void count(void)
{
   int n;

   // Count the characters to maintain the current column position
   if (swf5text[0] == '\n')
   {
      if (swf5debug) printf("\n");
   }
   else
   {
      if (swf5debug) printf("%s", swf5text);

      for(n=0; n<swf5leng; ++n, ++column)
      {
	if(column < 1023)
	  msgline[column] = swf5text[n];
      }

      //-- keep writing the stuff to standard output
      //column += swf5leng;
   }
}

static void printprog()
{
  if(sLineNumber)
    SWF_warn("\n%s", msgbufs[(sLineNumber-1)&1]);

  if(column < 1023)
    msgline[column] = 0;

  SWF_warn("\n%s", msgline);
}

static void warning(char *msg)
{
   // print a warning message
   printprog();
   SWF_warn("\n%*s", ColumnNumber(), "^");
   SWF_warn("\nLine %4.4d:  Reason: '%s' \n", LineNumber(), msg);
}

void swf5error(char *msg)
{
  // report a error
  if(strlen(swf5text))
  {
    SWF_error("\n%s\n%*s\nLine %i:  Reason: '%s'\n",
	      LineText(), ColumnNumber(), "^", LineNumber(), msg);
  }
  else
  {
    SWF_error("\nLine %d: Reason: 'Unexpected EOF found while looking for input.'\n", LineNumber());
  }
}

