.TH avi2swf "1" "January 2003" "avi2swf" "swftools"
.SH NAME
avi2swf - convert AVI files into SWF
.SH Synopsis
.B avi2swf
[\fIoptions\fR] \fIfile.avi\fR [-o \fIfile.swf\fR]
.SH DESCRIPTION
This tools converts AVI Video files into Flash SWF Animation
files.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print short help message and exit
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version info and exit
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Be verbose. Use more than one -v for greater effect.
.TP
\fB\-o\fR \fIfilename\fR, \fB\-\-output\fR \fIfilename\fR
Set output filename to \fIfilename\fR.
.TP
\fB\-p\fR, \fB\-\-flip\fR
Turn the movie upside down.
.TP
\fB\-x\fR, \fB\-\-extragood\fR
Enable highest-quality encoding. Warning: This is slow!
.TP
\fB\-S\fR \fIn\fR, \fB\-\-skip \fIn\fR\fR
Skip \fIn\fR frames before starting to encode.
.TP
\fB\-s\fR \fIfactor\fR, \fB\-\-scale \fIfactor\fR\fR
Scale movie by factor%. factor must be in the range 1-100.
.TP
\fB\-q\fR \fIq\fR, \fB\-\-quality\fR \fIq\fR
Set the compression quality to \fIq\fR. \fIq\fR must be
in the range 1-100. (1=worst, 100=best).

.SH AUTHOR

Matthias Kramm <kramm@quiss.org>
