/* aconf.h.  Generated by configure.  */
/*
 * aconf.h
 *
 * Copyright 2002 Glyph & Cog, LLC
 */

#ifndef ACONF_H
#define ACONF_H
#include "../../config.h"

#define HAVE_STRINGS_H 1

// todo:
//
// HAVE_STRINGS_H
// HAVE_BSTRING_H
// HAVE_SYS_SELECT_H
// SELECT_TAKES_INT
// HAVE_FSEEK64
// HAVE_MKSTEMPS

#endif
