.TH font2swf "1" "January 2003" "font2swf" "swftools"
.SH NAME
font2swf - convert Type 1 Font files to SWF
.SH Synopsis
.B font2swf font.afm
.SH DESCRIPTION
This tools converts Type 1 Fonts to SWF.
.SH BUGS
.PP
TrueType fonts don't work yet.
.TP
--help doesn't work.
.TP
The manpage could be a little more helpful. ;)

.SH AUTHOR

Matthias Kramm <kramm@quiss.org>
