.TH pdf2swf "1" "October 2001" "pdf2swf" "swftools"
.SH NAME
pdf2swf - convert PDF files into SWF
.SH Synopsis
.B pdf2swf
[\fIoptions\fR] \fIfile.pdf\fR -o \fIfile.swf\fR
.SH DESCRIPTION
This tools converts Acrobat PDF files into Flash SWF Animation
files.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print short help message and exit
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version info and exit
.TP
\fB\-p\fR, \fB\-\-pages\fR \fIrange\fR
Convert only pages in \fIrange\fR with \fIrange\fR e.g. 1-20 or 1,4,6,9-11 or
3-5,10-12
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Be verbose. Use more than one -v for greater effect.
.TP
\fB\-z\fR, \fB\-\-zlib\fR
Use Flash 6 (MX) zlib compression.
\fBThe resulting SWF will not be playable in browsers with Flash Plugins 5 and below!\fR
.TP
\fB\-i\fR, \fB\-\-ignore\fR
Allows pdf2swf to change the draw order of the pdf. This may make the generated
SWF files a little bit smaller, but it may also cause the images in the pdf to look funny.
.TP
\fB\-j\fR, \fB\-\-jpegquality\fR
Set quality of embedded jpeg pictures. 0 is worst (small), 100 is best (big). (default:85)
.TP
\fB\-w\fR, \fB\-\-samewindow\fR
When converting pdf hyperlinks, don't make the links open a new window when clicked on,
but open the page they point to in the window the SWF is displayed.
.TP
\fB\-F\fR, \fB\-\-fontdir\fR \fIdirectory\fR
Add \fIdirectory\fR to the font search path.
.TP
\fB\-b\fR, \fB\-\-defaultviewer\fR 
Link a standard viewer to the swf file. Therefore the swf file will be "browseable", i.e.
display some buttons for turning pages.
The viewer swf to be used is determined by a symlink named "default_viewer.swf" in
the swftools data directory.
.TP
\fB\-l\fR, \fB\-\-defaultloader\fR
Link a standard preloader to the swf file which will be displayed while the main swf is
loading.
The loader swf to be used is determined by a symlink named "default_loader.swf" in
the swftools data directory.
.TP
\fB\-B\fR, \fB\-\-viewer\fR \fIfilename\fR
Link viewer \fIfilename\fR to the swf file. See http://www.quiss.org/swftools/pdf2swf_usage.html
for information on how to create your own viewers.
.TP
\fB\-L\fR, \fB\-\-loader\fR \fIfilename\fR
Link preloader \fIfilename\fR to the swf file, where \fIfilename\fR
is an arbitrary swf animation.
.SH BUGS
.PP
dashed lines don't work.

.SH AUTHOR

Matthias Kramm <kramm@quiss.org>
