.TH jpeg2swf "1" "August 2009" "jpeg2swf" "swftools"
.SH NAME
jpeg2swf - Converts jpeg images to SWF.

.SH Synopsis
.B jpeg2swf [-options [value]] imagefiles[.jpg]|[.jpeg] [...]

.SH DESCRIPTION
This tool converts jpeg image files into an SWF animation. It takes any
number of input pictures, and converts them to SWF one-by-one, where every
converted picture is a seperate frame in the target SWF.

.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\fR \fIoutputfile\fR
    Explicitly specify output file. (Otherwise, output will go to stdout / output.swf)
.TP
\fB\-q\fR, \fB\-\-quality\fR \fIquality\fR
    Set compression quality (1-100, 1=worst, 100=best).
    This option can be set independently for each image.
.TP
\fB\-r\fR, \fB\-\-rate\fR \fIframerate\fR
    Set movie framerate (frames per second)
.TP
\fB\-z\fR, \fB\-\-zlib\fR \fIzlib\fR        
    Use Flash MX (SWF 6) Zlib encoding for the output. The resulting SWF will be
    smaller, but not playable in Flash Plugins of Version 5 and below.
.TP
\fB\-M\fR, \fB\-\-mx\fR 
    Use Flash MX H.263 compression (use for correlated images)
.TP
\fB\-x\fR, \fB\-\-xoffset\fR \fIoffset\fR  
    horizontally offset images by \fIoffset\fR
.TP
\fB\-y\fR, \fB\-\-yoffset\fR \fIoffset\fR  
    vertically offset images by \fIoffset\fR
.TP
\fB\-X\fR, \fB\-\-width\fR \fIwidth\fR   
    Force movie width to \fIwidth\fR (default: autodetect)
.TP
\fB\-Y\fR, \fB\-\-height\fR \fIheight\fR  
    Force movie height to \fIheight\fR (default: autodetect)
.TP
\fB\-T\fR, \fB\-\-flashversion\fR \fIversion\fR  
    Set flash file version to \fIversion\fR
.TP
\fB\-v\fR, \fB\-\-verbose\fR \fIlevel\fR 
    Set verbose level to \fIlevel\fR (0=quiet, 1=default, 2=debug)
.TP
\fB\-V\fR, \fB\-\-version\fR 
    Print version information and exit
.TP
\fB\-f\fR, \fB\-\-fit-to-movie\fR 
    Fit images to movie size
.TP
\fB\-e\fR, \fB\-\-export\fR \fIassetname\fR      
    Make importable as asset with \fIassetname\fR
.SH AUTHORS

Rainer Böhme <rfxswf@reflex-studio.de>
.TP
Matthias Kramm
