.TH png2swf "1" "April 2009" "png2swf" "swftools"
.SH NAME
png2swf - Takes a number of png files and converts them to a swf movie, one
picture per frame.

.SH Synopsis
.B png2swf [-X width] [-Y height] [-o file.swf] [-r rate] file1.png [file2.png...]

.SH DESCRIPTION
This tools converts png image files into an SWF animation. It takes any
number of input pictures, and converts them to SWF one-by-one, where every
converted picture is a seperate frame in the target SWF. 
.PP
The way the
images are encoded in SWF is very similar to PNG (in that a zlib-based, lossless
compression algorithm is used).

.SH OPTIONS
.TP
\fB\-r\fR, \fB\-\-rate\fR \fIframerate\fR
    Set movie framerate (frames per second)
.TP
\fB\-o\fR, \fB\-\-output\fR \fIfilename\fR
    Explicitly specify output file. (Otherwise, output will go to stdout / output.swf)
.TP
\fB\-j\fR, \fB\-\-jpeg\fR \fIquality\fR
    Generate a lossy jpeg bitmap inside the SWF, with a given quality (1-100)
.TP
\fB\-z\fR, \fB\-\-zlib\fR \fIzlib\fR        
    Use Flash MX (SWF 6) Zlib encoding for the output. The resulting SWF will be
    smaller, but not playable in Flash Plugins of Version 5 and below.
.TP
\fB\-T\fR, \fB\-\-flashversion\fR 
    Set the flash version to generate
.TP
\fB\-X\fR, \fB\-\-pixel\fR \fIwidth\fR
    Force movie width to \fIwidth\fR (default: autodetect)
.TP
\fB\-Y\fR, \fB\-\-pixel\fR \fIheight\fR
    Force movie height to \fIheight\fR (default: autodetect)
.TP
\fB\-v\fR, \fB\-\-verbose\fR \fIlevel\fR
    Set verbose level (0=quiet, 1=default, 2=debug)
.TP
\fB\-q\fR, \fB\-\-quiet\fR 
    Omit normal log messages, only log errors
.TP
\fB\-C\fR, \fB\-\-cgi\fR 
    For use as CGI- prepend http header, write to stdout
.TP
\fB\-V\fR, \fB\-\-version\fR 
    Print version information and exit
.TP
\fB\-s\fR, \fB\-\-scale\fR \fIpercent\fR
    Scale image to \fIpercent\fR% size.
.SH AUTHOR

Matthias Kramm <kramm@quiss.org>
