.TH swfbytes "1" "August 2009" "swfbytes" "swftools"
.SH NAME
swfbytes - Tool for simplifying the hex-editing of SWF files.

.SH Synopsis
.B swfbytes [-v] file.swf > file.hexdump
.PP
.B swfbytes file.hexdump

.SH DESCRIPTION
With this tool and a text editor, you can perform some basic
editing operations on SWF files.

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR 
    Print help and exit
.TP
\fB\-v\fR, \fB\-\-verbose\fR 
    Be more verbose
.TP
\fB\-V\fR, \fB\-\-version\fR 
    Print program version and exit
.SH AUTHOR

Matthias Kramm <kramm@quiss.org>
