.TH swfbbox "1" "April 2009" "swfbbox" "swftools"
.SH NAME
swfbbox - Tool for playing around with SWF bounding boxes.

.SH Synopsis
.B swfbbox [-OS] file.swf

.SH DESCRIPTION
This tool can, among others, recalculate some bounding boxes of SWFs
in order to speed them up or make them smaller.
.PP
It can also dump the corners of the bounding boxes of all frames of a movie.

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR 
    Print help and exit
.TP
\fB\-b\fR, \fB\-\-bbox\fR 
    Show movie bounding box (default)
.TP
\fB\-B\fR, \fB\-\-newbbox\fR 
    Show recalculated (optimized/expanded) bounding box
.TP
\fB\-e\fR, \fB\-\-expand\fR 
    Write out a new file using the recalculated header bounding box
.TP
\fB\-O\fR, \fB\-\-optimize\fR 
    Recalculate all object bounding boxes (except for the header)
.TP
\fB\-S\fR, \fB\-\-swifty\fR 
    Print out transformed bounding boxes
.TP
\fB\-c\fR, \fB\-\-clip\fR 
    Clip bounding boxes to movie size
.TP
\fB\-o\fR, \fB\-\-output\fR \fIfilename\fR
    Set output filename to \fIfilename\fR (for -O)
.TP
\fB\-v\fR, \fB\-\-verbose\fR 
    Be more verbose
.TP
\fB\-V\fR, \fB\-\-version\fR 
    Print program version and exit
.SH AUTHOR

Matthias Kramm <kramm@quiss.org>
