.TH swfdump "1" "October 2001" "swfdump" "swftools"
.SH NAME
swfdump - a tool for displaying information about flash files
.SH Synopsis
.B swfdump
[\fIoptions\fR] [\fIfile.swf\fR]
.SH DESCRIPTION
swfdump shows ids, names and depths of objects defined in the SWF file.
.PP
SWF files are animation files which can be displayed in Web Browsers using
the Flash Plugin.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print short help message and exit
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version info and exit
.TP
\fB\-e\fR, \fB\-\-html\fR
Print out html code for embedding the file
.TP
\fB\-a\fR, \fB\-\-action\fR
Disassemble action tags
.TP
\fB\-t\fR, \fB\-\-text\fR
Show text fields
.TP
\fB\-X\fR, \fB\-\-width\fR
Print out the horizontal dimension of the movie, in a string of the form "-X width"
.TP
\fB\-Y\fR, \fB\-\-height\fR
Print out the vertical dimension of the movie, in a string of the form "-Y height"
.TP
\fB\-r\fR, \fB\-\-rate\fR
Print out the frame rate of the movie, in a string of the form "-r rate"

.SH AUTHOR

Matthias Kramm <kramm@quiss.org>

