.TH swfdump "1" "April 2009" "swfdump" "swftools"
.SH NAME
swfdump - Display an SWF file's content.

.SH Synopsis
.B swfdump [-atpdu] file.swf

.SH DESCRIPTION
A tool for displaying information about flash files
.PP
swfdump shows ids, names and depths of objects defined in the SWF file.
It can furthermore also disassemble Actionscript, extract texts, and
display placement information about objects.

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR 
    Print short help message and exit
.TP
\fB\-D\fR, \fB\-\-full\fR 
    Show everything. Same as -atp
.TP
\fB\-V\fR, \fB\-\-version\fR 
    Print version info and exit
.TP
\fB\-e\fR, \fB\-\-html\fR 
    Print out html code for embedding the file
.TP
\fB\-E\fR, \fB\-\-xhtml\fR 
    Print out xhtml code for embedding the file
.TP
\fB\-a\fR, \fB\-\-action\fR 
    Disassemble action tags
.TP
\fB\-t\fR, \fB\-\-text\fR 
    Show text fields (like swfstrings).
.TP
\fB\-s\fR, \fB\-\-shapes\fR 
    Show shape coordinates/styles
.TP
\fB\-F\fR, \fB\-\-fonts\fR 
    Show font information
.TP
\fB\-p\fR, \fB\-\-placements\fR 
    Show placement information
.TP
\fB\-B\fR, \fB\-\-buttons\fR 
    Show button information
.TP
\fB\-b\fR, \fB\-\-bbox\fR 
    Print tag's bounding boxes
.TP
\fB\-X\fR, \fB\-\-width\fR 
    Print out the horizontal dimension of the movie, in a string of the form "-X width"
.TP
\fB\-Y\fR, \fB\-\-height\fR 
    Print out the vertical dimension of the movie, in a string of the form "-Y height"
.TP
\fB\-r\fR, \fB\-\-rate\fR 
    Print out the frame rate of the movie, in a string of the form "-r rate".
.TP
\fB\-f\fR, \fB\-\-frames\fR 
    Print out the number of frames in the movie, in a string of the form "-f frames"
.TP
\fB\-d\fR, \fB\-\-hex\fR 
    Print hex output of tag data, too.
.TP
\fB\-u\fR, \fB\-\-used\fR 
    Show referred IDs for each Tag.
.SH AUTHOR

Matthias Kramm <kramm@quiss.org>
