.TH swfdump "1" "October 2001" "swfdump" "swftools"
.SH NAME
swfdump - a tool for displaying information about flash files
.SH Synopsis
.B swfdump
[\fIoptions\fR] [\fIfile.swf\fR]
.SH DESCRIPTION
swfdump shows ids, names and depths of objects defined in the SWF file.
.PP
SWF files are animation files which can be displayed in Web Browsers using
the Flash Plugin.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print short help message and exit
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version info and exit
.TP
\fB\-a\fR, \fB\-\-action\fR
Disassemble action tags

.SH AUTHOR

Matthias Kramm <kramm@quiss.org>

