.TH swfextract "1" "October 2001" "swfdump" "swftools"
.SH NAME
swfextract - a tool for extracting data out of swf files.
.SH Synopsis
.B swfdump
[\fIoptions\fR] [\fIfile.swf\fR]
.SH DESCRIPTION
swfextracts allows to extract swf movieclips and objects out of swf files.
.PP
SWF files are animation files which can be displayed in Web Browsers using
the Flash Plugin.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print short help message and exit
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version info and exit
.TP
\fB\-i\fR, \fB\-\-id\fR \fIid\fR
Set the ID of the object to extract to \fIid\fR.
.TP
\fB\-n\fR, \fB\-\-name\fR \fIname\fR
Set the name of the object to extract to \fIname\fR.

.SH AUTHOR

Matthias Kramm <kramm@quiss.org>

