.TH swfstrings "1" "October 2001" "swfstrings" "swftools"
.SH NAME
swfstrings - a tool for extracting text out of swf files.
.SH Synopsis
.B swfstrings
[\fIoptions\fR] [\fIfile.swf\fR]
.SH DESCRIPTION
swfstrings extracts text out of DEFINETEXT tags of the .swf file. It also
displays the fonts being used.
.PP
SWF files are animation files which can be displayed in Web Browsers using
the Flash Plugin.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print short help message and exit
.\".TP
.\" \fB\-\-version\fR
.\" Print version info and exit

.SH AUTHOR

Rainer Böhme <rfxswf@reflex-studio.de>

