.TH wav2swf "1" "October 2001" "wav2swf" "swftools"
.SH NAME
wav2swf - convert a WAV file to an SWF animation
.SH Synopsis
.B wav2swf [-o file.swf] filename.wav
.SH DESCRIPTION
Takes a wav file and converts it to a swf movie.
.PP
(SWF files are animation files which can be displayed in Web Browsers using
the Flash Plugin)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print short help message and exit
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version info and exit
.TP
\fB\-o\fR, \fB\-\-output\fR \fIfilename\fR
Explicitly specify output file. (Otherwise, output will go to output.swf)
.TP
\fB\-f\fR, \fB\-\-framerate\fR \fIfps\fR
Set file framerate to \fIfps\fR frames per second.
.TP
\fB\-l\fR, \fB\-\-loop\fR \fIn\fR
(Only used with -d)
Loop the sound n times.
.TP
\fB\-d\fR, \fB\-\-definesound\fR
Store the sound as DEFINESOUND tag, not as streaming sound. Allows for
looping.

.SH AUTHORS

Matthias Kramm <kramm@quiss.org>

